### PR TITLE
fix deprecation warning

### PR DESCRIPTION
**Pull request by tzing**
# Description of change

Some of the imoprted classes from `collections` is moved to `collections.abc` and no longer acceptable in python 3.10

```txt
transit/class_hash.py:19
  /Users/tim_shih/Repos/python-stitch-client/transit/class_hash.py:19: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    class ClassDict(collections.MutableMapping):

transit/transit_types.py:15
transit/transit_types.py:15
  /Users/tim_shih/Repos/python-stitch-client/transit/transit_types.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Mapping, Hashable
```

and minor- found unused import so remove it

# Manual QA steps
 - Ran pytest on this branch and no new warning shows

# Risks
 - N/A

# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by setu4993** [comment]
@cosimon / someone else from the Stitch team: Can you help review and merge this?

This is blocking Python 3.10 support for us.

**Review by setu4993 — APPROVED** [review]

**Comment by JSeymore** [comment]
Is there an ETA on when this we be resolved?

**Comment by JSeymore** [comment]
> @cosimon / someone else from the Stitch team: Can you help review and merge this?
> 
> This is blocking Python 3.10 support for us.

Is there an ETA on when this will be resolved?

**Comment by cosimon** [comment]
Merged as part of PR #19

**Pull request closed without merging**
