### PR TITLE
Make dependencies flexible

### PR DESCRIPTION
**Pull request by setu4993**
# Description of change

The current dependency versions are very restrictive and make it difficult to use this client in environments with other dependencies.

# Manual QA steps
 - Ran `pytest` in a new Python 3.7 virtual env with the updated dependency list.
 
# Risks
 - N / A.
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by moredatarequired** [comment]
Or @cmerrick ? This is a simple fix for a definite pain point.

**Comment by benjamin-klara** [comment]
I hadn't seen this PR but it would exactly solve my issue (#16). It would be great if this could be merged, followed by a new release on PyPI.

**Comment by tpvitalilupusor** [comment]
Stitch team, can this be approved?  
Currently unable to use this package due to requirements conflict.

**Review by cosimon — APPROVED** [review]

**Comment by setu4993** [comment]
Thank you, @cosimon! I can see that the updated package is [published to pypi](https://pypi.org/project/stitchclient/1.0.1/).

Appreciate this.

**Pull request merged**
